export const FETCH_MAIN_NEWS = 'FETCH_MAIN_NEWS';
export const FETCH_TOP_NEWS = 'FETCH_TOP_NEWS';
export const FETCH_SELECTED_MAIN_NEWS = 'FETCH_SELECTED_MAIN_NEWS';
export const FETCH_SELECTED_TOP_NEWS = 'FETCH_SELECTED_TOP_NEWS'